title: Media Party Africa
description: > 
  : Cape Town, South Africa
  : October 21 - 23, 2016
  : Media Party Africa is hosted by the continent’s largest data journalism and civic technology federation, Code for Africa, in partnership with Hacks/Hackers Africa. Together, we're gathering some of the world’s most exciting civic technologists, digital journalists and other social justice watchdogs from across the world for three days of workshops and talks.

url: https://mediaparty.codeforafrica.org
enforce_ssl: mediaparty.codeforafrica.org
